export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MANY_CART = "ADD_MANY_CART";
export const REMOVE_CART = "REMOVE_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const ACTIVATE_CART = "ACTIVATE_CART";

export const CATEGORIES_UPDATE = "CATEGORIES_UPDATE";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
export const TOGGLE_CART ="TOGGLE_CART";
export const ADD_MULTIPLE_TO_CART ="ADD_MULTIPLE_TO_CART";